### ISSUE TITLE
sql.NullString

### ISSUE THREAD

**Issue by RoJo73** [godror/godror#168]
Great lib! 

Oracle since like version 8 supported null strings vs zero length strings / empty strings.

sql.NullString is not supported: Oracle DB does not differentiate between an empty string ("") and a NULL, so

create table example ( col1 varchar2(25 ), col2 number) ;
insert into example (col1, col2) values (null, 1);
insert into example (col1, col2) values ('', 2);
insert into example (col1, col2) values ('woh', 3);
insert into example (col2) values (4);

select * from example where col1 = '';
select * from example where col1 is null;
select * from example where length(col1) >= 0;

Maybe it's more of a Go thing having the default value of a string be '' or zero length...?

Great lib either way!

Thanks

**Comment by tgulacsi** [comment]
Sorry, but what is the question?

Oracle DB does not differentiate the empty string and the NULL value.
So, sql.NullString is pointless for Oracle DB.

    SELECT 1 FROM DUAL WHERE '' = ''

won't return anything, because NULL does not equal to anything -not even NULL.

    SELECT 1 FROM DUAL WHERE '' IS NULL

will return 1.

    SELECT LENGTH('') FROM DUAL

will return NULL, because length of NULL is NULL.
