### ISSUE TITLE
DB.Exec(...) Not Detecting All Placeholder Parameters in SQL String

### ISSUE THREAD

**Issue by hbingham037** [godror/godror#256]
**Describe the bug**
I create a sql string such as below

2022/10/21 12:59:05 INSERT_ALL WHEN :1 IS NOT NULL THEN INTO :2 (:3, :4, :5, :6, :7, :8) VALUES (:9, :10, :11, :12, :13, :14) WHEN :15 IS NOT NULL THEN INTO :16 (:17, :18, :19, :20, :21) VALUES (:22, :23, :24, :25, :26) WHEN :27 IS NOT NULL THEN INTO :28 (:29, :30, :31) VALUES (:32, :33, :34) WITH TEMP_INSERTION_TABLE AS ( SELECT :35 :36, :37 :38, NULL :39, NULL :40, NULL :41, NULL :42, :43 :44, :45 :46, NULL :47, NULL :48 FROM dual UNION ALL SELECT :49 :50, :51 :52, :53 :54, :55 :56, :57 :58, NULL :59, NULL :60, NULL :61, NULL :62, NULL :63, NULL :64, NULL :65 FROM dual) SELECT * FROM TEMP_INSERTION_TABLE

However, when I supply this, along with 65 arguments to DB.Exec, I get an error stating

2022/10/21 12:59:05 sql: expected 56 arguments, got 65

It seems like the argument missmatch is directly correlated to the amount of placeholder parameters used as values in the representation of the TEMP_INSERTION_TABLE . I've tested this and noticed that when N more placeholder parameters are used as values in the TEMP_INSERTION_TABLE, then the argument missmatch also increases by N

Is there any way I can remediate this?

**To Reproduce**
Create similar SQL string as provided in description, call Exec(sql_string, args)

**Expected behavior**
I expected the Exec function to not skip the detection of any of the placeholders for parameters

**Error output**
 sql: expected 56 arguments, got 65

**Your oracle client version**
I saw this in downlaods, not sure how to double check
instantclient-basic-linux.x64-19.8.0.0.0dbru.zip

**Your godror version**
e.g. v0.34.0

**Your go version**
e.g. 1.18.4

**Your gcc version**
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

**Machine (please complete the following information):**
 - OS:: Ubuntu
 - Architecture: x86_64
 - Version: Ubuntu 20.04 LTS

**Additional context**

**Comment by hbingham037** [comment]
I think I found a workaround. Instead of using placeholders for the COL in VAL COL, VAL COL, ... i started to write out the column string as a part of the SQL string instead of placeholder parameterizing it.

I also started to Prepare the statement, and then did statement.Exec(args), however, I don't think this caused any change, I think the former part of this comment did. So it seems the potential bug comes when BOTH VAL and COL are placeholders

**Comment by tgulacsi** [comment]
What should "NULL :47," be interpreted as?An alias is not a parameter.Feladó: hbingham037 ***@***.***>Elküldve: 2022. október 21., péntek 22:42Címzett: godror/godror ***@***.***>Másolat: Subscribed ***@***.***>Tárgy: [godror/godror] DB.Exec(...) Not Detecting All Placeholder Parameters in SQL String (Issue #256)
Describe the bug
I create a sql string such as below
2022/10/21 12:59:05 INSERT_ALL WHEN :1 IS NOT NULL THEN INTO :2 (:3, :4, :5, :6, :7, :8) VALUES (:9, :10, :11, :12, :13, :14) WHEN :15 IS NOT NULL THEN INTO :16 (:17, :18, :19, :20, :21) VALUES (:22, :23, :24, :25, :26) WHEN :27 IS NOT NULL THEN INTO :28 (:29, :30, :31) VALUES (:32, :33, :34) WITH TEMP_INSERTION_TABLE AS ( SELECT :35 :36, :37 :38, NULL :39, NULL :40, NULL :41, NULL :42, :43 :44, :45 :46, NULL :47, NULL :48 FROM dual UNION ALL SELECT :49 :50, :51 :52, :53 :54, :55 :56, :57 :58, NULL :59, NULL :60, NULL :61, NULL :62, NULL :63, NULL :64, NULL :65 FROM dual) SELECT * FROM TEMP_INSERTION_TABLE
However, when I supply this, along with 65 arguments to DB.Exec, I get an error stating
2022/10/21 12:59:05 sql: expected 56 arguments, got 65
It seems like the argument missmatch is directly correlated to the amount of placeholder parameters used as values in the representation of the TEMP_INSERTION_TABLE . I've tested this and noticed that when N more placeholder parameters are used as values in the TEMP_INSERTION_TABLE, then the argument missmatch also increases by N
Is there any way I can remediate this?
To Reproduce
Create similar SQL string as provided in description, call Exec(sql_string, args)
Expected behavior
I expected the Exec function to not skip the detection of any of the placeholders for parameters
Error output
sql: expected 56 arguments, got 65
Your oracle client version
I saw this in downlaods, not sure how to double check
instantclient-basic-linux.x64-19.8.0.0.0dbru.zip
Your godror version
e.g. v0.34.0
Your go version
e.g. 1.18.4
Your gcc version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Machine (please complete the following information):

OS:: Ubuntu
Architecture: x86_64
Version: Ubuntu 20.04 LTS

Additional context

**Comment by hbingham037** [comment]
This may not be a bug, but it just may be my misunderstanding on how Placeholder Expressions are used in Oracle SQL.

An example of potential (NULL :34) is (NULL First) below, where NULL is a value to be stored in a row and First is column name of that value. In original example I am trying to pass a column name as a Placeholder Expression, and First would be the 34th arg provided to db.Exec(...)

INSERT ALL
WHEN FIRST IS NOT NULL THEN
INTO HUNTER_FIRST (NAME, DESCRIPTION)
VALUES (First, Descr)
WHEN LAST IS NOT NULL THEN
INTO HUNTER_LAST (NAME, DESCRIPTION)
VALUES (LAST, DESCR)
  WITH names AS ( 
    SELECT 'Hunter' First, 'Dooood' Last, 'Buwwee' Descr   FROM dual UNION ALL 
    SELECT NULL First, 'Bingham' Last, 'Randomness' Descr  FROM dual UNION ALL 
    SELECT 'Jackson' First, NULL Last, 'Ysfss' Descr FROM dual
  )
SELECT * FROM names;

**Comment by cjbj** [comment]
> Instead of using placeholders for the COL in VAL COL, VAL COL, ... i started to write out the column string as a part of the SQL string instead of placeholder parameterizing it.

Bind variables can realistically only be used for data (without some funky uses of CASE)

**Comment by hbingham037** [comment]
Ok this is good to know, thank you for the help! And thanks team for the fast responses!
