### ISSUE TITLE
Setting TCP timeout for connection

### ISSUE THREAD

**Issue by VadimIpatov** [godror/godror#74]
Is there any way to set the tcp.connect_timeout parameter using godror interface?
The only way I've found is specify it in the sqlnet.ora.

Many drivers provide such functionality:
[https://github.com/lib/pq]()
`sql.Open("postgres", "user=user dbname=dbname connect_timeout=5")`
[https://github.com/go-sql-driver/mysql]()
`sql.Open("mysql", "user:password@/dbname?timeout=5s")`
[https://github.com/denisenkom/go-mssqldb]()
`sql.Open("sqlserver", "sqlserver://username:password@host/instance?dial+timeout=5")`

**Comment by tgulacsi** [comment]
I'm afraid that's the only possibility.
The other drivers speak the native protocol, we have to use a closed proprietary protocol through OCI, a C library.

[setCallTimeout](https://oracle.github.io/odpi/doc/functions/dpiConn.html#c.dpiConn_setCallTimeout) resembles what you seek, but first it is very hard to use (leaves the connection in an incosistent state), second maybe it's not low-level (TCP) enough: I'm afraid it needs a working TCP connection to cancel the operation...

What I've seen when connection to an unreachable host, it has terminated after 60s - if I recall, that's not what was set as poolTimeout, so I don't know how to modify that value.
Maybe pingTimeout of poolParams, but I don't know.

**Comment by cjbj** [comment]
[setCallTimeout ](https://oracle.github.io/odpi/doc/functions/dpiConn.html#c.dpiConn_setCallTimeout) is usable _after_ a connection has been created.  `tcp.connect_timeout` (and the related options like [`SQLNET.OUTBOUND_CONNECT_TIMEOUT`](https://www.oracle.com/pls/topic/lookup?ctx=dblatest&id=GUID-0857C817-675F-4CF0-BFBB-C3667F119176)) affect the time taken to open a connection to a DB.

The tech article [Oracle Database 19c Easy Connect Plus Configurable Database Connection
Syntax](https://download.oracle.com/ocomdocs/global/Oracle-Net-19c-Easy-Connect-Plus.pdf) shows options that might be usable, `"mydbmachine.example.com/orclpdb1?connect_timeout=15"`

@tgulacsi is there an example of using https://github.com/godror/godror/blob/f4c696919a06f4ecb983c22787af0430874170c9/drv.go#L155 somewhere?  Apps could write a `sqlnet.ora` at runtime and then pass the containing directory name to `configDir`.

**Comment by tgulacsi** [comment]
It's a "libDir" parameter in the connection string - it is used in the tests (z_test.go).
But you can set TNS_ADMIN anywhere before calling `sql.Open`.

**Comment by VadimIpatov** [comment]
Also it works if pass long DSN in the text form to driver:
 (DESCRIPTION= 
  (CONNECT_TIMEOUT=3)
   (ADDRESS=(PROTOCOL=tcp)(HOST=localhost)(PORT=1521))
  (CONNECT_DATA=
   (SERVICE_NAME=XE)))

**Comment by tgulacsi** [comment]
@VadimIpatov I have a beginning of a DESCRIPTION string parser (godror/godror/sid), bet I couldn't find a comprehensive description for all the possible parameters, so it is unfinished, incomplete.

**Comment by VadimIpatov** [comment]
> @VadimIpatov I have a beginning of a DESCRIPTION string parser (godror/godror/sid), bet I couldn't find a comprehensive description for all the possible parameters, so it is unfinished, incomplete.

Great! It would be very helpful thing.

Isn't this what you're looking for? https://docs.oracle.com/en/database/oracle/oracle-database/19/netrf/local-naming-parameters-in-tns-ora-file.html#GUID-7F967CE5-5498-427C-9390-4A5C6767ADAA

**Comment by tgulacsi** [comment]
@VadimIpatov I've checked and the tokenization works, but DescriptionList in sid/sid.go would need more params/options to be complete.

**Comment by tgulacsi** [comment]
@cjbj I've an idea: what if we separate the Oracle connection string from the driver's parameter string?
Now they're intermingled, but if we detach them, then they can evolve separately.

This would allow to have the Oracle connection string as OCI wishes: old format, simple format, Easy Connection format.. anything - we only need to parse the username and password from it, but that's feasible.

This would also allow to have an easier parameter string format: not the URL query encoded, but let's say as Postgres does it. A simple "keyword=value" list separated with whitespace. I think that's easier for the eyes.

The next thing is the separator: we can use a | (pipe), a ; (semicolon), a keyword ("pool:"), or,
if we can parse without ambiguity, without any.

If we can assume that the Oracle connection string dows not contain spaces, and it starts with "/" or contains "@", then we can mix it with the whitespace-separated keyword=value list.

Or for maximum safety, shall we separate them with "\n", and fix the order: first the Oracle connection string,
then the driver param list?

**Comment by sudarshan12s** [comment]
@tgulacsi <https://github.com/tgulacsi>,

how about being explicit about these two types of arguments, something like

un/pw@hostname
:1521/service_name:server/instance?connect_timeout=3&retry_count=3&godrorArgs={connectionClass=TestMyClass&standaloneConnection=0&poolMinSessions=0&poolMaxSessions=50&poolIncrement=1}
it impacts url with oracle prefix too

oracle://un:pw@hostname
:1521/service_name:server/instance?connect_timeout=3&retry_count=3&godrorArgs={connectionClass=TestMyClass&standaloneConnection=0&poolMinSessions=0&poolMaxSessions=50&poolIncrement=1}

**Comment by cjbj** [comment]
@tgulacsi the above is from a quick discussion with @sudarshan12s.  When @anthony-tuininga's day starts he may have more comments.

I have a vague recollection that the connection string may require spaces.  It certainly _could_ optionally have them e.g. in the `(DESCRIPTION=...` syntax.

FWIW, cx_Oracle parses  the username & password like [this](https://github.com/oracle/python-cx_Oracle/blob/8.0/src/cxoConnection.c#L722-L741).

**Comment by tgulacsi** [comment]
I've started an experiment ("connstring" branch), where the first line is the same as now,
but the second line is a logfmt-formatted (so simple "poolMax=3 poolMin=2 poolWait=5m" format) parameter list.

Almost as @sudarshan12s suggested, but separate from the connection string, which is the first line.
I've chosen logfmt, because it's easy on the eyes, and already used, so no new dependencies are needed.
I think it's better than URL-encoding or JSON.
https://github.com/godror/godror/issues/74#issuecomment-665446198 looks nicer than it is, as it is not correctly URL-encoded, which would look like 

    oracle://un:pw@hostname:1521/service_name:server/instance?connect_timeout=3&retry_count=3& \
        godrorArgs=%7BconnectionClass%3DTestMyClass%26standaloneConnection%3D0%26poolMinSessions%3D0%26poolMaxSessions%3D50%26poolIncrement%3D1%7D

My goal is to have the OCI connection string as a(n almost) black box (parsing only the username/password),
the same used with sqlplus.
This way this can evolve separately, and we can support Easy Connection Naming - or anyting not containing a "\n"!

But I'll wait for @anthony-tuininga 's insights before merging anyting!

**Comment by cjbj** [comment]
Will it allow nested quotes in any [easy connect syntax](https://download.oracle.com/ocomdocs/global/Oracle-Net-19c-Easy-Connect-Plus.pdf) component?

**Comment by tgulacsi** [comment]
It will allow anything that does not contain a new line.
The only exercise is to parse out the username and password. The rest is passed to ODPI as-is.

Or we can allow any string, without username/password, if they're specified on the second line, as parameters.
This would eliminate any need for parsing the connection string.

**Comment by anthony-tuininga** [comment]
@tgulacsi, your stated goal of having the OCI connection string as a black box makes sense and might be the safest approach long-term. Ideally, however, you would just use the same format for everything:

```
user=un password=pw dsn=hostname:1521/service_name:server/instance?connect_timeout=3&retry_count=3 connectionClass=TestMyClass standaloneConnection=0 poolMinSessions=0 poolMaxSessions=50 poolIncrement=1
```

If the dsn contained embedded spaces you would have to URL encode them (%20) or enclose the entire DSN in quotes. I don't think that is too onerous and not too commonly used anyway -- but if you'd rather just do it as you have it on your branch I don't have any strong objections.

If you do decide to proceed with the single format as I have suggested, you might be nice and allow the dsn to contain the user name and password which you have to parse out as cx_Oracle does.

**Comment by tgulacsi** [comment]
@anthony-tuininga you're right, and https://github.com/godror/godror/issues/74#issuecomment-665763318 is the beautiful thing to do.

The only issue with it is it is backwards-incompatible - the user have to know about the format change, understand it, prepare for it. 
The nicest would be a warning message that explains the new format, and convert from the old format, noting that it's deprecated. Later we could remove the old format parsing, changing the warning to an error.

But if we can parse the old format, and have to, then why not make the new format backwards-compatible?
That's why I settled on this "appended params" method - you can use the old formats without change,
augment them with the new parameters.

Of course the username/password is parsed from the DSN, if it's there.

I've added the "dsn" key parsing, allowing a logfmt-only nice connectiong string you showed us! 
So now you can use 
  - any old format,
  - any old format with appended parameters,
  - only the new, parameters format.

Of course this flexibility comes with complexity and code bloat, but I don't want to change my connection strings in my dozens of programs and libraries.

**Comment by tgulacsi** [comment]
More ore less - a little bit more lax:
  - if there are "\n", treat the first line as old/easy/anything that goes into DSN, the second line as parameters list
  - if it's only one line, and there's "dsn=", then try to parse it as parameters list, otherwise use it as DSN (assume its only for OCI).

Always try to parse out the user/passw@ from the DSN, but don't overwrite if it's there from the parameters list.

You're right about the documentation: we should document only the new format, and mention the old only as a footnote.

**Comment by anthony-tuininga** [comment]
Seems reasonable.

**Comment by tgulacsi** [comment]
Ok. Shall I merge it, or should we wait for more insights, comments? 
@VadimIpatov do you want to try it?

**Comment by anthony-tuininga** [comment]
Maybe create a PR so that we can see all of the changes? And include the documentation in that PR? @cjbj may have other comments -- but I'm good based on what you described!

**Comment by cjbj** [comment]
I would personally prefer the README doc to show the logfmt example password (and username) in quotes, which may help someone who has whitespace in their password.  Something like `username="scott" password="tiger" ...`

Both cx_Oracle and node-oracledb use `user` instead of `username`.  (Though I kind-of like `username`).

The Oracle Net team internally doesn't use the term 'dsn' but call it 'connect descriptor' (although technically that is the name of the string to the right of the "=" in a tnsnames.ora file).  They suggested using something like `connectString` for a generic argument name.  This is what we used in [node-oracledb](https://oracle.github.io/node-oracledb/doc/api.html#createpoolpoolattrsconnectstring).    There may never be a perfect name since it can be overloaded, but `connectString` is at least a little more readable.

I would also suggest you don't use `dsn` because  [database/sql already documents](https://golang.org/pkg/database/sql/#Open) its second parameter as `dataSourceName` -  you may want to change the current use of `sql.Open("godror", connString)`to `sql.Open("godror", dataSourceNmae)` to be consistent with database/sql.

**Comment by tgulacsi** [comment]
@cjbj I've changed as you suggested. PTAL https://github.com/godror/godror/pull/77

**Comment by cjbj** [comment]
I will take a look and send you some text that may help you for the readme.

One typo I saw is that `libDir` should be `configDir`.  The libDir param should be the library location, and configDir should be the TNS_ADMIN equivalant.

**Comment by tgulacsi** [comment]
@VadimIpatov it's in master, you can test it!

**Comment by VadimIpatov** [comment]
It works great! Thanks guys

**Comment by VadimIpatov** [comment]
It works great! Thanks guys
